import { useState, type FormEvent, type ReactNode } from 'react';
import { Plus, Trash2, Upload, Camera, Copy, ArrowUpRight, Check, AlertTriangle } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { useMoney } from '@/lib/money/context';
import { accountBalance, equalSplit, findDuplicate, formatMoney, minor } from '@/lib/money/calculations';
import { connected, receiptScanner, moneyService } from '@/lib/money/service';
import type { Collection, MoneyData, Transaction, TransactionType, Status } from '@/lib/money/types';
import { MoneyAmount, Segments, TransactionStatus } from './ui';
const today=()=>new Date().toISOString().slice(0,10);
export function Sheet({open,onClose,title,description,children}:{open:boolean;onClose:()=>void;title:string;description?:string;children:ReactNode}){return <Dialog open={open} onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="sheet-content"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description||'Review your details before saving.'}</DialogDescription></DialogHeader>{children}</DialogContent></Dialog>}
export function TransactionForm({open,onClose,initial,type='Expense',scan=false}:{open:boolean;onClose:()=>void;initial?:Transaction;type?:TransactionType;scan?:boolean}){
 const {data,save,remove}=useMoney();const [kind,setKind]=useState<TransactionType>(initial?.type||type);const [name,setName]=useState(initial?.name||'');const [amount,setAmount]=useState(initial?String(initial.amount/100):'');const [account,setAccount]=useState(initial?.accountId||data.accounts.find(a=>!a.archived)?.id||'');const [destination,setDestination]=useState(initial?.destinationId||'');const [category,setCategory]=useState(initial?.category||'Food');const [date,setDate]=useState(initial?.date.slice(0,10)||today());const [notes,setNotes]=useState(initial?.notes||'');const [status,setStatus]=useState<Status>(initial?.status|| (type==='Payment'||scan?'Needs Verification':'Confirmed'));const [method,setMethod]=useState(initial?.method||'UPI');const [reference,setReference]=useState(initial?.reference||'');const [busy,setBusy]=useState(false);const [duplicate,setDuplicate]=useState<Transaction>();const [pending,setPending]=useState<Transaction>();const [attachment,setAttachment]=useState(initial?.attachment||'');const [warning,setWarning]=useState('');const [confirmDelete,setConfirmDelete]=useState(false);const [changeConfirm,setChangeConfirm]=useState(false);
 const commit=async(candidate:Transaction,replace?:Transaction)=>{setBusy(true);if(replace) candidate={...candidate,id:replace.id};const ok=await save('transactions',candidate);setBusy(false);if(ok)onClose()};
 const submit=(e:FormEvent)=>{e.preventDefault();const value=minor(amount);if(!Number.isFinite(value)||value<=0){setWarning('Enter an amount greater than zero.');return}if(!account){setWarning('Create an account before adding a transaction.');return}if(kind==='Transfer'&&(!destination||account===destination)){setWarning('Choose a different destination account.');return}const source=data.accounts.find(a=>a.id===account);if(source&&['Expense','Payment','Transfer','Investment'].includes(kind)&&status==='Confirmed'&&source.type!=='Credit Card'&&value>accountBalance(source,data.transactions)+(initial?.amount||0)){setWarning('This amount exceeds the available account balance.');return}const candidate:Transaction={id:initial?.id||crypto.randomUUID(),name:name.trim()||category,amount:value,type:kind,accountId:account,destinationId:kind==='Transfer'?destination:undefined,category,date:date+'T12:00:00',notes,status,method,reference,attachment};const dupe=findDuplicate(data.transactions,candidate);if(dupe){setDuplicate(dupe);setPending(candidate);return}if(initial&&value!==initial.amount&&!changeConfirm){setPending(candidate);setChangeConfirm(true);return}void commit(candidate)};
 const scanFile=async(file?:File)=>{if(!file)return;setAttachment(file.name);setBusy(true);try{const result=await receiptScanner.extract(file);if(result.name)setName(result.name);if(result.amount)setAmount(String(result.amount/100));if(result.date)setDate(result.date.slice(0,10));if(result.reference)setReference(result.reference);setStatus('Needs Verification')}catch(e){setWarning(e instanceof Error?e.message:'Enter the receipt details manually.')}finally{setBusy(false)}};
 return <Sheet open={open} onClose={onClose} title={duplicate?'Possible duplicate transaction':changeConfirm?'Confirm amount change':initial?'Transaction details':scan?'Review receipt':'Add transaction'} description={scan?'Confirm the receipt details before adding to your activity.':undefined}>{duplicate&&pending?<div className="form-stack"><div className="finance-panel"><label>Existing transaction</label><p>{duplicate.name} · <MoneyAmount amount={duplicate.amount}/></p><p className="text-xs text-muted-foreground mt-2">{duplicate.date.slice(0,10)} · {duplicate.status}</p></div><div><label>New transaction</label><p>{pending.name} · <MoneyAmount amount={pending.amount}/></p></div><Button variant="secondary" onClick={onClose}>Keep existing</Button><Button variant="outline" onClick={()=>void commit(pending,duplicate)}>Replace existing</Button><Button onClick={()=>void commit(pending)}>Keep both</Button></div>:changeConfirm&&pending?<div className="form-stack"><p>Change <MoneyAmount amount={initial?.amount||0}/> to <MoneyAmount amount={pending.amount}/>?</p><Button onClick={()=>void commit(pending)} disabled={busy}>Confirm change</Button><Button variant="secondary" onClick={()=>setChangeConfirm(false)}>Go back</Button></div>:<form onSubmit={submit} className="form-stack">
 {!initial&&<Segments options={['Expense','Income','Transfer','Payment']} value={kind} onChange={v=>{setKind(v as TransactionType);setStatus(v==='Payment'?'Needs Verification':'Confirmed')}}/>}
 {scan&&<div className="grid grid-cols-2 gap-3"><Button variant="secondary" asChild><label className="cursor-pointer text-foreground m-0"><Camera/> Take photo<input type="file" accept="image/*" capture="environment" className="hidden" onChange={e=>void scanFile(e.target.files?.[0])}/></label></Button><Button variant="secondary" asChild><label className="cursor-pointer text-foreground m-0"><Upload/> Choose receipt<input type="file" accept="image/*" className="hidden" onChange={e=>void scanFile(e.target.files?.[0])}/></label></Button></div>}
 <div><label htmlFor="tx-amount">Amount ({data.currency})</label><input id="tx-amount" className="amount-input" inputMode="decimal" type="number" min="0.01" step="0.01" required placeholder="0.00" value={amount} onChange={e=>{setAmount(e.target.value);setWarning('')}} autoFocus/></div>
 <div><label htmlFor="tx-name">{kind==='Income'?'Received from':'Merchant or description'}</label><input id="tx-name" placeholder={kind==='Income'?'Salary, freelance, or other income':'What was it for?'} value={name} onChange={e=>setName(e.target.value)}/></div>
 <div className="field-grid"><div><label htmlFor="tx-category">Category</label><select id="tx-category" value={category} onChange={e=>setCategory(e.target.value)}>{data.categories.map(c=><option key={c}>{c}</option>)}</select></div><div><label htmlFor="tx-account">{kind==='Transfer'?'From account':'Account'}</label><select id="tx-account" required value={account} onChange={e=>setAccount(e.target.value)}><option value="" disabled>Select account</option>{data.accounts.filter(a=>!a.archived).map(a=><option value={a.id} key={a.id}>{a.institution} · {a.name}</option>)}</select></div></div>
 {kind==='Transfer'&&<div><label htmlFor="tx-destination">To account</label><select id="tx-destination" required value={destination} onChange={e=>setDestination(e.target.value)}><option value="">Select destination</option>{data.accounts.filter(a=>a.id!==account&&!a.archived).map(a=><option key={a.id} value={a.id}>{a.institution} · {a.name}</option>)}</select></div>}
 <div className="field-grid"><div><label htmlFor="tx-date">Date</label><input id="tx-date" type="date" required value={date} onChange={e=>setDate(e.target.value)}/></div><div><label htmlFor="tx-method">Payment method</label><select id="tx-method" value={method} onChange={e=>setMethod(e.target.value)}>{['UPI','Cash','Bank transfer','Card','GPay','PhonePe','Paytm','BHIM','Other'].map(m=><option key={m}>{m}</option>)}</select></div></div>
 {(initial||kind==='Payment'||scan)&&<div><label htmlFor="tx-status">Payment status</label><select id="tx-status" value={status} onChange={e=>setStatus(e.target.value as Status)}>{['Draft','Pending','Confirmed','Failed','Cancelled','Needs Verification'].map(s=><option key={s}>{s}</option>)}</select>{status==='Confirmed'&&<p className="text-xs text-positive mt-2">Only confirm a payment you know has completed.</p>}</div>}
 <details className="text-xs text-muted-foreground"><summary className="cursor-pointer py-1">Notes & payment information</summary><div className="form-stack mt-4"><div><label htmlFor="tx-notes">Notes</label><textarea id="tx-notes" value={notes} onChange={e=>setNotes(e.target.value)}/></div><div><label htmlFor="tx-ref">Reference ID</label><div className="flex gap-2"><input id="tx-ref" value={reference} onChange={e=>setReference(e.target.value)}/>{reference&&<Button type="button" variant="secondary" size="icon" title="Copy reference" onClick={()=>{void navigator.clipboard.writeText(reference);toast.success('Reference copied')}}><Copy/></Button>}</div></div>{attachment&&<p>Attachment: {attachment}</p>}</div></details>
 {warning&&<p role="alert" className="text-warning text-xs flex items-start gap-2"><AlertTriangle size={16} className="shrink-0"/>{warning}</p>}
 <Button type="submit" disabled={busy||!data.accounts.length}>{busy?'Saving…':initial?'Save changes':scan?'Confirm & add':kind==='Payment'?'Save for verification':'Save transaction'}</Button>
 {initial&&<Button type="button" variant="ghost" className="text-destructive" onClick={()=>{if(confirmDelete){void remove('transactions',initial.id);onClose()}else setConfirmDelete(true)}}><Trash2/>{confirmDelete?'Confirm delete transaction':'Delete transaction'}</Button>}
 </form>}</Sheet>
}
const entityConfig:Record<string,{title:string;fields:{key:string;label:string;type?:string;options?:string[];required?:boolean}[]}>={
 accounts:{title:'account',fields:[{key:'name',label:'Account name',required:true},{key:'institution',label:'Institution',required:true},{key:'type',label:'Account type',options:['Bank','Cash','Wallet','Credit Card','Investment','Other']},{key:'opening',label:'Opening balance',type:'money'},{key:'limit',label:'Credit limit (credit cards only)',type:'money'}]},
 budgets:{title:'budget',fields:[{key:'name',label:'Budget name',required:true},{key:'category',label:'Category',type:'category'},{key:'amount',label:'Monthly allocation',type:'money',required:true}]},
 goals:{title:'goal',fields:[{key:'name',label:'Goal name',required:true},{key:'amount',label:'Target amount',type:'money',required:true},{key:'current',label:'Already saved',type:'money'},{key:'date',label:'Target date',type:'date',required:true}]},
 recurring:{title:'recurring payment',fields:[{key:'name',label:'Payment name',required:true},{key:'amount',label:'Amount',type:'money',required:true},{key:'date',label:'Next due date',type:'date',required:true},{key:'frequency',label:'Frequency',options:['Monthly','Weekly','Yearly','Quarterly','One-time']},{key:'accountId',label:'Payment account',type:'account'},{key:'category',label:'Category',type:'category'}]},
 people:{title:'person',fields:[{key:'name',label:'Name',required:true},{key:'relation',label:'Relationship',options:['Partner','Parent','Daughter','Son','Sibling','Friend','Roommate','Other']}]},
 spaces:{title:'shared space',fields:[{key:'name',label:'Space name',required:true},{key:'kind',label:'Space type',options:['Family','Couple','Roommates','Trip','Household','Custom']}]},
 investments:{title:'investment',fields:[{key:'name',label:'Investment name',required:true},{key:'kind',label:'Asset class',options:['Stocks','Mutual Funds','ETFs','Bonds','Fixed Deposits','Government securities','REITs','Retirement','Other']},{key:'amount',label:'Amount invested',type:'money',required:true},{key:'current',label:'Current value',type:'money',required:true}]},
 assets:{title:'asset',fields:[{key:'name',label:'Asset name',required:true},{key:'kind',label:'Asset type',options:['Gold','Property','Vehicle','Other']},{key:'amount',label:'Purchase value',type:'money',required:true},{key:'current',label:'Estimated current value',type:'money',required:true},{key:'weight',label:'Gold weight (grams)',type:'number'},{key:'purity',label:'Gold purity',options:['Not applicable','24K','22K','18K']}]},
 liabilities:{title:'liability',fields:[{key:'name',label:'Liability name',required:true},{key:'kind',label:'Debt type',options:['Education loan','Personal loan','Vehicle loan','Home loan','Money owed','Other debt']},{key:'amount',label:'Original amount',type:'money',required:true},{key:'current',label:'Outstanding amount',type:'money',required:true}]}
};
export function EntityForm({collection,initial,onClose}:{collection:Collection;initial?:{id:string};onClose:()=>void}){
 const {data,save,remove}=useMoney();const config=entityConfig[collection];const [values,setValues]=useState<Record<string,string>>(()=>{const item=initial as unknown as Record<string,unknown>|undefined;return Object.fromEntries((config?.fields||[]).map(f=>[f.key,item?.[f.key]!==undefined?String(f.type==='money'?Number(item[f.key])/100:item[f.key]):f.options?.[0]||(f.type==='date'?today():f.type==='category'?data.categories[0]:f.type==='account'?data.accounts[0]?.id||'':'')]))});const [members,setMembers]=useState<string[]>((initial as unknown as {memberIds?:string[]})?.memberIds||[]);const [busy,setBusy]=useState(false);const [deleting,setDeleting]=useState(false);const [reminder,setReminder]=useState(true);
 if(!config)return null;
 const submit=async(e:FormEvent)=>{e.preventDefault();const item:Record<string,unknown>={id:initial?.id||crypto.randomUUID()};for(const f of config.fields){item[f.key]=f.type==='money'?minor(values[f.key]||0):f.type==='number'?Number(values[f.key]||0):values[f.key];if((f.required&&f.type==='money'&&Number(item[f.key])<=0)||(['money','number'].includes(f.type||'')&&!Number.isFinite(Number(item[f.key])))){toast.error(`Enter a valid ${f.label.toLowerCase()}.`);return}}if(collection==='goals'&&Number(item.current)>Number(item.amount)){toast.error('Saved amount cannot exceed the goal target.');return}if(collection==='spaces')item.memberIds=members;if(collection==='recurring')item.reminder=reminder;if(initial)Object.assign(item,{...(initial as object),...item});setBusy(true);const ok=await save(collection,item as unknown as MoneyData[typeof collection][number]);setBusy(false);if(ok)onClose()};
 return <Sheet open onClose={onClose} title={`${initial?'Edit':'Add'} ${config.title}`}><form onSubmit={submit} className="form-stack">{config.fields.map(f=><div key={f.key}><label htmlFor={`entity-${f.key}`}>{f.label}{f.type==='money'?` (${data.currency})`:''}</label>{f.options||f.type==='category'||f.type==='account'?<select id={`entity-${f.key}`} required={f.required||f.type==='account'} value={values[f.key]||''} onChange={e=>setValues(v=>({...v,[f.key]:e.target.value}))}>{f.type==='account'?<><option value="" disabled>Select account</option>{data.accounts.filter(a=>!a.archived).map(a=><option key={a.id} value={a.id}>{a.institution} · {a.name}</option>)}</>:(f.type==='category'?['All',...data.categories]:f.options||[]).map(o=><option key={o}>{o}</option>)}</select>:<input id={`entity-${f.key}`} required={f.required} type={f.type==='money'||f.type==='number'?'number':f.type||'text'} min={f.type==='money'&&f.key!=='opening'?0:undefined} step={f.type==='money'||f.type==='number'?'0.01':undefined} value={values[f.key]||''} onChange={e=>setValues(v=>({...v,[f.key]:e.target.value}))}/>}</div>)}
 {collection==='spaces'&&<div><label>Members</label>{data.people.length===0?<p className="text-xs text-muted-foreground">Add people to include them in this space.</p>:data.people.map(p=><label key={p.id} className="flex items-center gap-3 text-foreground py-1"><input type="checkbox" checked={members.includes(p.id)} onChange={e=>setMembers(m=>e.target.checked?[...m,p.id]:m.filter(id=>id!==p.id))}/>{p.name}</label>)}</div>}
 {collection==='recurring'&&<label className="flex items-center gap-3"><input type="checkbox" checked={reminder} onChange={e=>setReminder(e.target.checked)}/>Remind me 3 days before and on the due date</label>}
 <Button disabled={busy} type="submit">{busy?'Saving…':`Save ${config.title}`}</Button>
 {initial&&<Button type="button" variant="ghost" className="text-destructive" onClick={()=>{if(collection==='accounts'&&data.transactions.some(t=>t.accountId===initial.id||t.destinationId===initial.id)){toast.error('This account has transactions. Archive it instead.');return}if(deleting){void remove(collection,initial.id);onClose()}else setDeleting(true)}}><Trash2/>{deleting?'Confirm removal':`Delete ${config.title}`}</Button>}
 </form></Sheet>
}
export function AddEntity({collection,label}:{collection:Collection;label?:string}){const [open,setOpen]=useState(false);return <><Button onClick={()=>setOpen(true)}><Plus/>{label||'Add new'}</Button>{open&&<EntityForm collection={collection} onClose={()=>setOpen(false)}/>}</>}
export function SplitForm({onClose}:{onClose:()=>void}){const {data,save}=useMoney();const [name,setName]=useState('');const [amount,setAmount]=useState('');const [space,setSpace]=useState(data.spaces[0]?.id||'');const [account,setAccount]=useState(data.accounts[0]?.id||'');const [mode,setMode]=useState('Equal');const [shares,setShares]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);const members=data.spaces.find(s=>s.id===space)?.memberIds||[];const ids=['you',...members];const portions=mode==='Equal'?equalSplit(minor(amount||0),ids.length):ids.map(id=>mode==='Percentage'?Math.round(minor(amount||0)*Number(shares[id]||0)/100):minor(shares[id]||0));
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!space||!account||minor(amount)<=0||portions.reduce((s,n)=>s+n,0)!==minor(amount)){toast.error('Shares must add up to the total amount.');return}setBusy(true);const transactionId=crypto.randomUUID();const ok=await save('transactions',{id:transactionId,name,amount:minor(amount),category:'Food',accountId:account,type:'Expense',status:'Confirmed',date:today()+'T12:00:00',spaceId:space,notes:'Shared expense paid by you'});if(ok){for(let i=0;i<members.length;i++){const person=data.people.find(p=>p.id===members[i]);await save('settlements',{id:`${transactionId}-${members[i]}`,name:person?.name||'Member',amount:portions[i+1],paid:false,spaceId:space,accountId:account})}onClose()}setBusy(false)};
 return <Sheet open onClose={onClose} title="Split an expense" description="Only this shared expense is visible to space members."><form onSubmit={submit} className="form-stack"><div><label htmlFor="split-name">Description</label><input id="split-name" required value={name} onChange={e=>setName(e.target.value)} placeholder="Dinner, groceries, a trip…"/></div><div><label htmlFor="split-amount">Total amount · paid by you</label><input id="split-amount" required type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></div><div className="field-grid"><div><label htmlFor="split-space">Shared space</label><select id="split-space" required value={space} onChange={e=>setSpace(e.target.value)}><option value="" disabled>Select space</option>{data.spaces.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div><label htmlFor="split-account">Paid from</label><select id="split-account" required value={account} onChange={e=>setAccount(e.target.value)}><option value="" disabled>Select account</option>{data.accounts.map(a=><option key={a.id} value={a.id}>{a.institution} · {a.name}</option>)}</select></div></div><Segments options={['Equal','Percentage','Exact amount']} value={mode} onChange={setMode}/>{ids.map((id,i)=><div className="grid grid-cols-[minmax(0,1fr)_100px] items-center gap-3" key={id}><p className="text-sm">{id==='you'?'You':data.people.find(p=>p.id===id)?.name||'Member'}</p>{mode==='Equal'?<MoneyAmount amount={portions[i]} className="text-sm text-right"/>:<input aria-label={`${id==='you'?'Your':data.people.find(p=>p.id===id)?.name} share`} type="number" min="0" step="0.01" value={shares[id]||''} onChange={e=>setShares(s=>({...s,[id]:e.target.value}))}/>}</div>)}<Button type="submit" disabled={busy||!data.spaces.length||!data.accounts.length}>{busy?'Saving…':'Confirm & split'}</Button></form></Sheet>
}
export function UploadDocument(){const {save}=useMoney();const [busy,setBusy]=useState(false);return <Button variant="secondary" asChild><label className="cursor-pointer text-foreground m-0"><Upload/>{busy?'Uploading…':'Upload document'}<input type="file" className="hidden" accept=".pdf,image/*,.csv" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>20*1024*1024){toast.error('Choose a file smaller than 20 MB.');return}setBusy(true);try{if(connected)await moneyService.upload(file);await save('documents',{id:crypto.randomUUID(),name:file.name,size:file.size,kind:file.type,date:today()});if(!connected)toast.info('Demo stores file information only. Secure uploads require your backend.')}catch{toast.error('Could not upload the document.')}finally{setBusy(false)}}}/></label></Button>}
