import { Link } from '@tanstack/react-router';
import { useState } from 'react';
import { Plus, ArrowDownLeft, ArrowUpRight, ScanLine, CircleCheck, Clock3, CalendarDays, AlertCircle, ChevronRight, ShieldCheck, SlidersHorizontal, Wallet, Ellipsis, Coffee } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useMoney } from '@/lib/money/context';
import { accountBalance, categorySpent, summary } from '@/lib/money/calculations';
import type { Transaction, TransactionType } from '@/lib/money/types';
import { MoneyAmount, PageHeading, SectionHeading, Progress, TransactionRow, EmptyState } from './ui';
import { TransactionForm, Sheet, AddEntity } from './forms';
export function HomeView(){
 const {data,loading,error,reload}=useMoney();const s=summary(data);const [form,setForm]=useState<{type:TransactionType;scan?:boolean | undefined;initial?:Transaction | undefined}>();const [customize,setCustomize]=useState(false);const [visible,setVisible]=useState({budget:true,accounts:true,goals:true});const recent=[...data.transactions].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);const attention=s.attention[0];
 if(loading)return <div className="animate-pulse grid gap-6"><div className="h-10 w-1/2 bg-muted rounded"/><div className="h-56 bg-card rounded"/><div className="h-64 bg-card rounded"/></div>;
 if(error)return <EmptyState title="Your money couldn’t be loaded" text={error} action={<Button onClick={reload}>Try again</Button>}/>;
 return <><PageHeading title={`Good ${new Date().getHours()<12?'morning':new Date().getHours()<17?'afternoon':'evening'}, ${data.profile}`} subtitle="A little clarity for your everyday money."><div className="flex gap-2 items-center"><span className="desktop-only text-xs text-muted-foreground mr-2">{new Date().toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}</span><Button variant="ghost" size="icon" onClick={()=>setCustomize(true)} aria-label="Customize home" title="Customize home"><SlidersHorizontal size={17}/></Button></div></PageHeading>
 <div className="home-grid"><div className="home-left"><section className="balance-card"><h2>Spendable money</h2><div className="balance-number"><MoneyAmount amount={s.spendable}/><span className="text-foreground/60 text-[26px]">.00</span></div><span className="balance-mark"><Wallet strokeWidth={1.2} size={26}/></span><div className="balance-footer"><div className="flex gap-1.5 items-center"><ShieldCheck size={13}/><span>After your upcoming commitments</span></div><Link to="/accounts" className="text-foreground no-underline flex items-center gap-1">Your accounts <ArrowUpRight size={12}/></Link></div></section>
 <div className="quick-actions">{[{label:'Add expense',icon:Plus,type:'Expense' as const},{label:'Add income',icon:ArrowDownLeft,type:'Income' as const},{label:'Transfer',icon:ArrowUpRight,type:'Transfer' as const},{label:'Scan receipt',icon:ScanLine,type:'Expense' as const,scan:true}].map(a=><Button variant="secondary" key={a.label} className="quick-action" onClick={()=>setForm({type:a.type,scan:a.scan})}><a.icon strokeWidth={1.5}/>{a.label}</Button>)}</div>
 <div className="metrics"><div className="metric"><p className="metric-label"><ArrowUpRight size={12}/>Today’s spending</p><MoneyAmount className="metric-number" amount={s.today}/><p className="metric-foot">A fresh start, every day</p></div><Link to="/upcoming" className="metric text-foreground no-underline"><p className="metric-label"><CalendarDays size={12}/>Upcoming</p><MoneyAmount className="metric-number" amount={s.upcoming}/><p className="metric-foot">Due this month <ChevronRight size={10} className="inline"/></p></Link><Link to="/payments" className="metric text-foreground no-underline"><p className="metric-label"><AlertCircle size={12}/>Needs attention</p><p className="metric-number text-warning">{s.attention.length} <span className="text-sm">{s.attention.length===1?'item':'items'}</span></p><p className="metric-foot">{s.attention.length?'Let’s take a look':'All caught up'} <ChevronRight size={10} className="inline"/></p></Link></div>
 {attention&&<section className="attention-panel"><div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3"><div className="min-w-0 flex gap-10 sm:gap-3"><AlertCircle size={17} className="text-warning shrink-0 hidden sm:block"/><div className="min-w-0"><p className="text-xs font-medium">Did your payment go through?</p><p className="text-[10px] text-muted-foreground mt-1.5 truncate">{attention.name} · <MoneyAmount amount={attention.amount}/></p></div></div><Button variant="ghost" size="sm" className="text-warning text-[11px]" onClick={()=>setForm({type:attention.type,initial:attention})}>Review <ArrowUpRight size={12}/></Button></div></section>}
 <section><SectionHeading title="Recent activity" to="/activity"/><div className="finance-panel pt-2">{recent.length?recent.map(t=><TransactionRow key={t.id} transaction={t} onClick={()=>setForm({type:t.type,initial:t})}/>):<EmptyState title="A fresh start" text="Your transactions will appear here." action={<AddEntity collection="accounts" label="Add your first account"/>}/>}</div></section>
 <section className="finance-panel"><SectionHeading title="This month, at a glance" to="/activity" action="View activity"/><div className="flex gap-12 mt-5"><div><p className="text-[10px] text-muted-foreground mb-2">Money in</p><MoneyAmount amount={s.income} className="text-lg text-positive"/></div><div><p className="text-[10px] text-muted-foreground mb-2">Money out</p><MoneyAmount amount={s.spent} className="text-lg"/></div><div className="ml-auto hidden sm:block"><p className="text-[10px] text-muted-foreground mb-2">Savings rate</p><p className="text-lg">{s.income>0?Math.round((s.income-s.spent)/s.income*100):0}%</p></div></div></section>
 </div><div className="home-right">
 <section><SectionHeading title="Coming up" to="/upcoming"/><div className="finance-panel pt-1">{data.recurring.filter(r=>!r.paid).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,3).map((r,i)=><div className="transaction-row" key={r.id}><div className="category-icon"><CalendarDays size={16} className={i===0?'text-primary':'text-muted-foreground'}/></div><div className="min-w-0"><p className="transaction-name">{r.name}</p><p className="transaction-caption">{new Date(r.date).toLocaleDateString('en-GB',{day:'numeric',month:'short'})} · {r.frequency.toLowerCase()}</p></div><MoneyAmount amount={r.amount} className="text-xs"/></div>)}{data.recurring.length===0&&<p className="text-xs text-muted-foreground py-6">No upcoming payments.</p>}</div></section>
 {visible.budget&&<section><SectionHeading title="Your monthly budgets" to="/budgets"/><div className="finance-panel">{data.budgets.map((b,i)=>{const spent=categorySpent(data,b.category);return <div className="budget-row" key={b.id}><div className="budget-row-header"><span>{b.name}</span><span className="text-[10px] text-muted-foreground"><MoneyAmount amount={spent}/> <span className="text-muted-foreground/50">/ <MoneyAmount amount={b.amount}/></span></span></div><Progress value={spent} max={b.amount} tone={spent>b.amount?'progress-warning':i===0?'progress-positive':i===1?'progress-info':'progress-violet'}/><div className="budget-caption"><span>{Math.round(spent/b.amount*100)}% used</span><span>{spent>b.amount?'Over budget':`${Math.round((b.amount-spent)/100).toLocaleString('en-IN')} left`}</span></div></div>})}{!data.budgets.length&&<p className="text-xs text-muted-foreground">No budgets yet.</p>}<Link to="/budgets" className="subtle-link justify-center border-t border-border pt-4 mt-5">Keep a little room for what matters <ArrowUpRight size={11}/></Link></div></section>}
 {visible.accounts&&<section><SectionHeading title="Where your money is" to="/accounts"/><div className="finance-panel pt-1">{data.accounts.filter(a=>!a.hidden&&!a.archived).map(a=><div className="account-mini" key={a.id}><div className={`institution-logo ${a.type==='Cash'?'cash':''}`}>{a.type==='Cash'?<Wallet size={15}/>:a.institution}</div><div className="min-w-0"><p className="text-xs truncate">{a.name}</p><p className="transaction-caption">{a.type}</p></div><MoneyAmount amount={accountBalance(a,data.transactions)} className="text-xs"/></div>)}{!data.accounts.length&&<AddEntity collection="accounts" label="Add account"/>}</div></section>}
 {visible.goals&&data.goals[0]&&<section className="finance-panel"><SectionHeading title="A little closer to your goal" to="/goals"/><div className="flex gap-3 items-center mb-5"><div className="category-icon text-primary"><ShieldCheck size={18}/></div><div><p className="text-xs">{data.goals[0].name}</p><p className="transaction-caption"><MoneyAmount amount={data.goals[0].current}/> of <MoneyAmount amount={data.goals[0].amount}/></p></div><span className="ml-auto text-sm text-primary">{Math.round(data.goals[0].current/data.goals[0].amount*100)}%</span></div><Progress value={data.goals[0].current} max={data.goals[0].amount}/></section>}
 </div></div>
 {form&&<TransactionForm key={form.initial?.id||`${form.type}-${form.scan}`} open type={form.type} scan={form.scan} initial={form.initial} onClose={()=>setForm(undefined)}/>}
 <Sheet open={customize} onClose={()=>setCustomize(false)} title="Make home your own" description="Choose the summaries you want to see.">{(['budget','accounts','goals'] as const).map(k=><label key={k} className="flex items-center justify-between text-sm text-foreground py-3"><span>{k==='budget'?'Monthly budgets':k==='accounts'?'Account balances':'Savings goals'}</span><input type="checkbox" checked={visible[k]} onChange={e=>setVisible(v=>({...v,[k]:e.target.checked}))}/></label>)}</Sheet>
 </>
}
