import { Link, useRouterState } from '@tanstack/react-router';
import { useState, useEffect, type ReactNode } from 'react';
import { Home, ArrowLeftRight, Wallet, CreditCard, Repeat, ChartNoAxesColumnIncreasing, Target, CalendarDays, Users, UserRound, HandCoins, TrendingUp, Gem, Landmark, ChartPie, Files, Bell, Settings, Search, ScanLine, ArrowUpRight, CloudOff } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { SidebarProvider } from '@/components/ui/sidebar';
import { Avatar, AvatarImage, AvatarFallback } from '@/components/ui/avatar';
import { Badge } from '@/components/ui/badge';
import { useMoney } from '@/lib/money/context';
import profile from '@/assets/profile.jpg';
import { TransactionForm } from './forms';
import { AnimatedContent, FloatingNavigation, Hint } from './presentation';
import { DesktopNavigation } from './desktop-navigation';
import { GlobalSearch } from './search';
const groups=[{name:'Main',items:[{label:'Home',path:'/',icon:Home},{label:'Activity',path:'/activity',icon:ArrowLeftRight}]},{name:'Money',items:[{label:'Accounts',path:'/accounts',icon:Wallet},{label:'Payments',path:'/payments',icon:CreditCard},{label:'Recurring',path:'/recurring',icon:Repeat}]},{name:'Plan',items:[{label:'Budgets',path:'/budgets',icon:ChartNoAxesColumnIncreasing},{label:'Goals',path:'/goals',icon:Target},{label:'Upcoming',path:'/upcoming',icon:CalendarDays}]},{name:'People',items:[{label:'Shared',path:'/shared',icon:Users},{label:'People',path:'/people',icon:UserRound},{label:'Settlements',path:'/settlements',icon:HandCoins}]},{name:'Wealth',items:[{label:'Investments',path:'/investments',icon:TrendingUp},{label:'Assets',path:'/assets',icon:Gem},{label:'Liabilities',path:'/liabilities',icon:Landmark},{label:'Net Worth',path:'/net-worth',icon:ChartPie}]},{name:'System',items:[{label:'Documents',path:'/documents',icon:Files},{label:'Notifications',path:'/notifications',icon:Bell},{label:'Settings',path:'/settings',icon:Settings}]}];
export function MoneyShell({ children }: { children: ReactNode }) {
 const { data, demo, online } = useMoney();
 const path = useRouterState({ select: s => s.location.pathname });
 const [open, setOpen] = useState(true);
 const [scanner, setScanner] = useState(false);
 const [search, setSearch] = useState(false);
 const current = groups.flatMap(g => g.items).find(i => i.path === path)?.label || (path === '/plan' ? 'Plan' : 'More');
 const unread = data.notifications.filter(n => !n.read).length;
 useEffect(() => { const key = (e: KeyboardEvent) => { if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'k') { e.preventDefault(); setSearch(s => !s); } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, []);
 return <SidebarProvider open={open} onOpenChange={setOpen} className={`money-shell ${open ? '' : 'sidebar-collapsed'}`}><DesktopNavigation/><div className="app-main"><header className="topbar"><div className="flex min-w-0 items-center gap-3"><p className="topbar-title">{current}</p><Link to="/settings" className="mobile-brand hidden" aria-label="Your profile"><Avatar className="size-9"><AvatarImage src={profile} alt="Your profile"/><AvatarFallback>{data.profile.slice(0,1)}</AvatarFallback></Avatar></Link>{demo && <Badge variant="outline" className="demo-label">Demo session</Badge>}{!online && <span className="text-warning text-xs flex gap-1"><CloudOff size={12}/>Offline</span>}</div><div className="flex items-center gap-2"><Button variant="ghost" className="desktop-only text-muted-foreground text-xs" onClick={() => setSearch(true)}><Search size={15}/>Search your money<span className="search-shortcut">⌘ K</span></Button><Hint label="Search Money OS"><Button variant="secondary" size="icon" className="mobile-brand hidden" aria-label="Search Money OS" onClick={() => setSearch(true)}><Search/></Button></Hint><Hint label="Scan receipt"><Button variant="secondary" size="icon" aria-label="Scan receipt" onClick={() => setScanner(true)}><ScanLine/></Button></Hint><Hint label="Notifications"><Button variant="secondary" size="icon" asChild className="relative"><Link to="/notifications" aria-label="Notifications"><Bell/>{unread > 0 && <span className="notice-badge"/>}</Link></Button></Hint></div></header><main key={path} className="main-content"><AnimatedContent>{children}</AnimatedContent></main></div><FloatingNavigation/>{scanner && <TransactionForm open scan onClose={() => setScanner(false)}/>}<GlobalSearch open={search} onClose={() => setSearch(false)}/></SidebarProvider>;
}
export function NavigationDirectory({section='more'}:{section?:'more'|'plan'}){const selected=section==='plan'?groups.filter(g=>g.name==='Plan'||g.name==='Money').map(g=>({...g,items:g.items.filter(i=>section!=='plan'||['Budgets','Goals','Upcoming','Recurring'].includes(i.label))})):groups.filter(g=>g.name!=='Main');return <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-7">{selected.map(g=><section key={g.name}>{g.items.length>0&&<h2 className="text-xs text-muted-foreground uppercase mb-3">{g.name}</h2>}{g.items.map(i=><Link to={i.path} key={i.path} className="setting-row no-underline text-foreground"><div className="flex items-center gap-4"><i.icon className="text-muted-foreground" size={19}/><span className="text-sm">{i.label}</span></div><ArrowUpRight size={15} className="text-muted-foreground"/></Link>)}</section>)}</div>}
