import { Link, useRouterState } from '@tanstack/react-router';
import { useState, type ReactNode } from 'react';
import { Home, ArrowLeftRight, Wallet, CreditCard, Repeat, ChartNoAxesColumnIncreasing, Target, CalendarDays, Users, UserRound, HandCoins, TrendingUp, Gem, Landmark, ChartPie, Files, Bell, Settings, PanelLeftClose, PanelLeftOpen, Search, ScanLine, MoreHorizontal, LayoutGrid, ChevronDown, ArrowUpRight, X, CloudOff } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useMoney } from '@/lib/money/context';
import profile from '@/assets/profile.jpg';
import { TransactionForm, Sheet } from './forms';
import { AnimatedContent, FloatingNavigation, Hint } from './presentation';
import { formatMoney } from '@/lib/money/calculations';
const groups=[{name:'Main',items:[{label:'Home',path:'/',icon:Home},{label:'Activity',path:'/activity',icon:ArrowLeftRight}]},{name:'Money',items:[{label:'Accounts',path:'/accounts',icon:Wallet},{label:'Payments',path:'/payments',icon:CreditCard},{label:'Recurring',path:'/recurring',icon:Repeat}]},{name:'Plan',items:[{label:'Budgets',path:'/budgets',icon:ChartNoAxesColumnIncreasing},{label:'Goals',path:'/goals',icon:Target},{label:'Upcoming',path:'/upcoming',icon:CalendarDays}]},{name:'People',items:[{label:'Shared',path:'/shared',icon:Users},{label:'People',path:'/people',icon:UserRound},{label:'Settlements',path:'/settlements',icon:HandCoins}]},{name:'Wealth',items:[{label:'Investments',path:'/investments',icon:TrendingUp},{label:'Assets',path:'/assets',icon:Gem},{label:'Liabilities',path:'/liabilities',icon:Landmark},{label:'Net Worth',path:'/net-worth',icon:ChartPie}]},{name:'System',items:[{label:'Documents',path:'/documents',icon:Files},{label:'Notifications',path:'/notifications',icon:Bell},{label:'Settings',path:'/settings',icon:Settings}]}];
export function MoneyShell({children}:{children:ReactNode}){
 const {data,demo,online}=useMoney();const path=useRouterState({select:s=>s.location.pathname});const [collapsed,setCollapsed]=useState(false);const [scanner,setScanner]=useState(false);const [search,setSearch]=useState(false);const [query,setQuery]=useState('');const current=groups.flatMap(g=>g.items).find(i=>i.path===path)?.label||(path==='/plan'?'Plan':'More');const unread=data.notifications.filter(n=>!n.read).length;
 const planActive=['/plan','/budgets','/goals','/upcoming','/recurring'].includes(path);const sharedActive=['/shared','/people','/settlements'].includes(path);const moreActive=!['/','/activity'].includes(path)&&!planActive&&!sharedActive;
 return <div className={collapsed?'sidebar-collapsed':''}><aside className="app-sidebar"><Link to="/" className="sidebar-brand text-foreground no-underline"><span className="brand-symbol">m</span><span className="brand-text">money os<span className="text-primary">.</span></span></Link><nav className="sidebar-scroll" aria-label="Main navigation">{groups.map(g=><div key={g.name}><p className="nav-group">{g.name}</p>{g.items.map(i=><Link key={i.path} to={i.path} activeOptions={{exact:true}} className="nav-link" title={collapsed?i.label:undefined}><i.icon size={17} strokeWidth={1.6}/><span className="nav-label">{i.label}</span>{i.label==='Notifications'&&unread>0&&!collapsed&&<span className="ml-auto text-[10px] text-primary">{unread}</span>}</Link>)}</div>)}</nav><div className="sidebar-bottom"><Button variant="ghost" size="icon" onClick={()=>setCollapsed(v=>!v)} aria-label={collapsed?'Expand navigation':'Collapse navigation'} title={collapsed?'Expand navigation':'Collapse navigation'}>{collapsed?<PanelLeftOpen/>:<PanelLeftClose/>}</Button><Link to="/settings" className="flex items-center gap-3 mt-3 px-1 no-underline text-foreground"><img src={profile} alt="Profile" width={32} height={32} className="w-8 h-8 shrink-0 rounded-full object-cover"/><div className="sidebar-profile-text min-w-0"><p className="text-xs truncate">{data.profile}</p><p className="text-[10px] text-muted-foreground mt-1">Personal account</p></div><ChevronDown size={12} className="sidebar-profile-text ml-auto text-muted-foreground"/></Link></div></aside>
  <div className="app-main"><header className="topbar"><div className="flex min-w-0 items-center gap-3"><p className="topbar-title">{current}</p><Link to="/settings" className="mobile-brand hidden"><img src={profile} alt="Your profile" width={30} height={30} className="w-[30px] h-[30px] rounded-full object-cover"/></Link>{demo&&<span className="demo-label">Demo session</span>}{!online&&<span className="text-warning text-[10px] flex gap-1"><CloudOff size={12}/>Offline</span>}</div><div className="flex items-center gap-2 shrink-0"><Button variant="ghost" className="desktop-only text-muted-foreground mr-3 text-xs" onClick={()=>setSearch(true)}><Search size={15}/>Search activity<span className="text-[10px] border border-border px-1.5 py-0.5 rounded ml-6">⌕</span></Button><Hint label="Search activity"><Button variant="secondary" size="icon" className="mobile-brand hidden" aria-label="Search activity" onClick={()=>setSearch(true)}><Search/></Button></Hint><Hint label="Scan receipt"><Button variant="secondary" size="icon" aria-label="Scan receipt" onClick={()=>setScanner(true)}><ScanLine/></Button></Hint><Button variant="secondary" size="icon" asChild className="relative"><Link to="/notifications" aria-label="Notifications" title="Notifications"><Bell/>{unread>0&&<span className="notice-badge"/>}</Link></Button></div></header><main key={path} className="main-content"><AnimatedContent>{children}</AnimatedContent></main></div>
 <FloatingNavigation/> 
 {scanner&&<TransactionForm open scan onClose={()=>setScanner(false)}/>}
 <Sheet open={search} onClose={()=>setSearch(false)} title="Search activity" description="Search your merchant, amount, account, or reference."><div className="search-field"><Search/><input aria-label="Search all transactions" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your transactions…" autoFocus/></div><div className="max-h-80 overflow-y-auto">{data.transactions.filter(t=>query&&[t.name,t.category,t.notes,t.reference,String(t.amount/100),data.accounts.find(a=>a.id===t.accountId)?.institution].some(v=>v?.toLowerCase().includes(query.toLowerCase()))).map(t=><Link to="/activity" key={t.id} onClick={()=>setSearch(false)} className="setting-row no-underline text-foreground"><div><p className="text-sm">{t.name}</p><p className="text-xs text-muted-foreground mt-1">{t.category} · {t.status}</p></div><span className="text-sm">{formatMoney(t.amount,data.currency)}</span></Link>)}{query&&!data.transactions.some(t=>t.name.toLowerCase().includes(query.toLowerCase())||t.category.toLowerCase().includes(query.toLowerCase()))&&<p className="text-xs text-muted-foreground pt-4">No matching merchants or categories.</p>}</div></Sheet>
 </div>
}
export function NavigationDirectory({section='more'}:{section?:'more'|'plan'}){const selected=section==='plan'?groups.filter(g=>g.name==='Plan'||g.name==='Money').map(g=>({...g,items:g.items.filter(i=>section!=='plan'||['Budgets','Goals','Upcoming','Recurring'].includes(i.label))})):groups.filter(g=>g.name!=='Main');return <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-7">{selected.map(g=><section key={g.name}>{g.items.length>0&&<h2 className="text-xs text-muted-foreground uppercase mb-3">{g.name}</h2>}{g.items.map(i=><Link to={i.path} key={i.path} className="setting-row no-underline text-foreground"><div className="flex items-center gap-4"><i.icon className="text-muted-foreground" size={19}/><span className="text-sm">{i.label}</span></div><ArrowUpRight size={15} className="text-muted-foreground"/></Link>)}</section>)}</div>}
