import { Link } from '@tanstack/react-router';
import { ArrowDownLeft, ArrowUpRight, ShoppingBag, Utensils, Car, Repeat, Zap, CircleCheck, Clock3, AlertCircle, Wallet, type LucideIcon } from 'lucide-react';
import type { ReactNode } from 'react';
import { Button } from '@/components/ui/button';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Progress as UiProgress } from '@/components/ui/progress';
import { Badge } from '@/components/ui/badge';
import { useMoney } from '@/lib/money/context';
import { formatMoney } from '@/lib/money/calculations';
import type { Status, Transaction } from '@/lib/money/types';
export function MoneyAmount({amount,className='',decimals=false}:{amount:number;className?:string;decimals?:boolean}) { const {data}=useMoney();return <span className={className}>{decimals?new Intl.NumberFormat('en-IN',{style:'currency',currency:data.currency,minimumFractionDigits:2,maximumFractionDigits:2}).format(amount/100):formatMoney(amount,data.currency)}</span> }
export function PageHeading({title,subtitle,children}:{title:string;subtitle?:string;children?:ReactNode}) {return <div className="page-heading"><div className="min-w-0"><h1>{title}</h1>{subtitle&&<p className="page-subtitle">{subtitle}</p>}</div><div className="shrink-0">{children}</div></div>}
export function SectionHeading({title,to,action='View all'}:{title:string;to?:string;action?:string}) {return <div className="section-heading"><h2>{title}</h2>{to&&<Link to={to} className="subtle-link">{action}<ArrowUpRight size={12}/></Link>}</div>}
export function EmptyState({title,text,action,icon:Icon=Wallet}:{title:string;text:string;action?:ReactNode;icon?:LucideIcon}) {return <div className="empty-state"><Icon/><h2>{title}</h2><p>{text}</p>{action}</div>}
export function Progress({value,max=100,tone=''}:{value:number;max?:number;tone?:string}){return <UiProgress aria-label="Progress" className={`progress-track h-1.5 ${tone}`} value={Math.max(0,Math.min(100,(value/(max||1))*100))}/>}
export function TransactionStatus({status}:{status:Status}) {const Icon=status==='Confirmed'?CircleCheck:['Failed','Needs Verification'].includes(status)?AlertCircle:Clock3;return <Badge variant="outline" className={`transaction-status gap-1 status-${status.replaceAll(' ','')}`}><Icon size={10}/>{status}</Badge>}
export function CategoryIcon({category,type}:{category:string;type?:string}) {const Icon=type==='Income'?ArrowDownLeft:category==='Food'?Utensils:category==='Transport'?Car:category==='Shopping'?ShoppingBag:category==='Subscriptions'?Repeat:category==='Bills'?Zap:ArrowUpRight;return <span className={`category-icon ${type==='Income'?'income':category.toLowerCase()}`}><Icon size={17}/></span>}
export function TransactionRow({transaction:t,onClick}:{transaction:Transaction;onClick:()=>void}) {const {data}=useMoney();const account=data.accounts.find(a=>a.id===t.accountId);return <div className="transaction-row"><CategoryIcon category={t.category} type={t.type}/><div className="min-w-0"><Button variant="link" className="transaction-name p-0 h-auto text-foreground max-w-full justify-start" onClick={onClick}>{t.name}</Button><div className="transaction-caption">{t.category} <span className="mx-1">·</span> {account?.institution||'Account'} {t.spaceId&&'· Shared'}</div></div><div><div className={`transaction-amount ${t.type==='Income'||(t.type==='Settlement'&&t.destinationId)?'text-positive':''}`}>{t.type==='Income'||(t.type==='Settlement'&&t.destinationId)?'+':'−'}<MoneyAmount amount={t.amount}/></div><div className="text-right mt-1">{t.status==='Confirmed'?<span className="transaction-caption">{new Date(t.date).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</span>:<TransactionStatus status={t.status}/>}</div></div></div>}
export function Segments({options,value,onChange}:{options:string[];value:string;onChange:(value:string)=>void}) {return <Tabs value={value} onValueChange={onChange}><TabsList className="segmented h-auto flex-wrap rounded-full p-1" aria-label="View options">{options.map(o=><TabsTrigger key={o} value={o} className={`segment rounded-full ${value===o?'selected':''}`}>{o}</TabsTrigger>)}</TabsList></Tabs>}
export function StatBand({items}:{items:{label:string;amount:number;tone?:string}[]}){return <div className="stat-band">{items.map(i=><div key={i.label}><label>{i.label}</label><MoneyAmount amount={i.amount} className={`stat-value block ${i.tone||''}`}/></div>)}</div>}
