import { Link } from '@tanstack/react-router';
import { ArrowDownLeft, ArrowUpRight, ShoppingBag, Utensils, Car, Repeat, Zap, CircleCheck, Clock3, AlertCircle, Wallet, type LucideIcon } from 'lucide-react';
import type { ReactNode } from 'react';
import { Button } from '@/components/ui/button';
import { useMoney } from '@/lib/money/context';
import { formatMoney } from '@/lib/money/calculations';
import type { Status, Transaction } from '@/lib/money/types';
export function MoneyAmount({amount,className=''}:{amount:number;className?:string}) { const {data}=useMoney();return <span className={className}>{formatMoney(amount,data.currency)}</span> }
export function PageHeading({title,subtitle,children}:{title:string;subtitle?:string;children?:ReactNode}) {return <div className="page-heading"><div className="min-w-0"><h1>{title}</h1>{subtitle&&<p className="page-subtitle">{subtitle}</p>}</div><div className="shrink-0">{children}</div></div>}
export function SectionHeading({title,to,action='View all'}:{title:string;to?:string;action?:string}) {return <div className="section-heading"><h2>{title}</h2>{to&&<Link to={to} className="subtle-link">{action}<ArrowUpRight size={12}/></Link>}</div>}
export function EmptyState({title,text,action,icon:Icon=Wallet}:{title:string;text:string;action?:ReactNode;icon?:LucideIcon}) {return <div className="empty-state"><Icon/><h2>{title}</h2><p>{text}</p>{action}</div>}
export function Progress({value,max=100,tone=''}:{value:number;max?:number;tone?:string}){return <div className={`progress-track ${tone}`}><progress max={max||1} value={Math.max(0,Math.min(value,max||1))}/></div>}
export function TransactionStatus({status}:{status:Status}) {const Icon=status==='Confirmed'?CircleCheck:['Failed','Needs Verification'].includes(status)?AlertCircle:Clock3;return <span className={`transaction-status status-${status.replaceAll(' ','')}`}><Icon size={10}/>{status}</span>}
export function CategoryIcon({category,type}:{category:string;type?:string}) {const Icon=type==='Income'?ArrowDownLeft:category==='Food'?Utensils:category==='Transport'?Car:category==='Shopping'?ShoppingBag:category==='Subscriptions'?Repeat:category==='Bills'?Zap:ArrowUpRight;return <span className={`category-icon ${type==='Income'?'income':category.toLowerCase()}`}><Icon size={17}/></span>}
export function TransactionRow({transaction:t,onClick}:{transaction:Transaction;onClick:()=>void}) {const {data}=useMoney();const account=data.accounts.find(a=>a.id===t.accountId);return <div className="transaction-row"><CategoryIcon category={t.category} type={t.type}/><div className="min-w-0"><Button variant="link" className="transaction-name p-0 h-auto text-foreground max-w-full justify-start" onClick={onClick}>{t.name}</Button><div className="transaction-caption">{t.category} <span className="mx-1">·</span> {account?.institution||'Account'} {t.spaceId&&'· Shared'}</div></div><div><div className={`transaction-amount ${t.type==='Income'?'text-positive':''}`}>{t.type==='Income'?'+':'−'}<MoneyAmount amount={t.amount}/></div><div className="text-right mt-1">{t.status==='Confirmed'?<span className="transaction-caption">{new Date(t.date).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</span>:<TransactionStatus status={t.status}/>}</div></div></div>}
export function Segments({options,value,onChange}:{options:string[];value:string;onChange:(value:string)=>void}) {return <div className="segmented">{options.map(o=><Button key={o} variant="ghost" className={`segment ${value===o?'selected':''}`} onClick={()=>onChange(o)}>{o}</Button>)}</div>}
export function StatBand({items}:{items:{label:string;amount:number;tone?:string}[]}){return <div className="stat-band">{items.map(i=><div key={i.label}><label>{i.label}</label><MoneyAmount amount={i.amount} className={`stat-value block ${i.tone||''}`}/></div>)}</div>}
